---
name: Docker
on:
  pull_request:
    branches:
      - main
    paths:
      - 'docker/*'

jobs:
  build:
    name: Build Dockerfile
    runs-on: ubuntu-latest
    outputs:
      dockerfile_changed: ${{ steps.filter.outputs.docker }}
    steps:
      - name: Checkout repo ⤵️
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # test that the Dockerfile builds at all
      # CircleCI handles pushes for now
      - name: Build Image
        uses: docker/build-push-action@b32b51a8eda65d6793cd0494a773d4f6bcef32dc # v6.11.0
        with:
          file: docker/Dockerfile
          context: .
          push: false
          tags: khulnasoft/kernel-crawler:test
