---
name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      crawler_changed: ${{ steps.filter.outputs.crawler }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            crawler:
              - 'kernel_crawler/**'

  test:
    name: test kernel-crawler
    runs-on: ubuntu-latest
    needs: paths-filter
    if: needs.paths-filter.outputs.crawler_changed == 'true'
    steps:
      - name: Checkout repo ⤵️
        uses: actions/checkout@v3

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install python3 python3-pip python3-pygit2 jq

      - name: Install crawler
        run: |
          pip3 install .

      - name: Run crawler
        run: |
          kernel-crawler crawl --distro "*" > kernels.json

      - name: Validate json
        run: |
          cat kernels.json | jq empty

      - uses: actions/upload-artifact@v3
        with:
          path: kernels.json
