---
name: Update Kernels

on:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * *'

# Checks if any concurrent jobs is running for kernels CI and eventually cancel it.
concurrency:
  group: kernels-ci
  cancel-in-progress: true

jobs:
  update-kernels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout crawler
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run crawler for x86_64
        id: crawler_x86_64
        uses: ./
        with:
          arch: 'x86_64'

      - name: Run crawler for aarch64
        id: crawler_aarch64
        uses: ./
        with:
          arch: 'aarch64'

      - name: Move generated files to site folder
        run: |
          mkdir site/x86_64
          mv ${{ steps.crawler_x86_64.outputs.json }} site/x86_64/list.json
          mkdir site/aarch64
          mv ${{ steps.crawler_aarch64.outputs.json }} site/aarch64/list.json

      - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: 'site'

      - id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
